"use strict";
var app_components_util_1 = require('./app-components.util');
exports.APP_COMPONENTS = [
    app_components_util_1.ActivityListComponent,
    app_components_util_1.AgenciesComponent,
    app_components_util_1.AgencyComponent,
    app_components_util_1.AgencySidebarComponent,
    app_components_util_1.AppComponent,
    app_components_util_1.BannerArtComponent,
    app_components_util_1.CapacityComponent,
    app_components_util_1.CapacityBasicsComponent,
    app_components_util_1.CapacityCollaborationComponent,
    app_components_util_1.CapacityInteragencySharingComponent,
    app_components_util_1.CapacityIntroductionComponent,
    app_components_util_1.CapacityResourcesComponent,
    app_components_util_1.CapacitySecurityComponent,
    app_components_util_1.ComplianceComponent,
    app_components_util_1.ComplianceAcquiringCodeComponent,
    app_components_util_1.ComplianceInventoryCodeComponent,
    app_components_util_1.ComplianceLicensingComponent,
    app_components_util_1.ComplianceMeasuringCodeComponent,
    app_components_util_1.ComplianceMetadataSchemaComponent,
    app_components_util_1.ComplianceWhatsRequiredComponent,
    app_components_util_1.DocsComponent,
    app_components_util_1.ExploreCodeComponent,
    app_components_util_1.FourOhFourComponent,
    app_components_util_1.HomeComponent,
    app_components_util_1.IntroductionComponent,
    app_components_util_1.ModalComponent,
    app_components_util_1.OverviewComponent,
    app_components_util_1.OverviewInventoryComponent,
    app_components_util_1.OverviewPilotComponent,
    app_components_util_1.OverviewTrackingProgressComponent,
    app_components_util_1.PolicyGuideComponent,
    app_components_util_1.PrivacyPolicyComponent,
    app_components_util_1.RepoComponent,
    app_components_util_1.ReposComponent
];
//# sourceMappingURL=components-array.util.js.map